### ISSUE TITLE
Unbox TArray

### ISSUE THREAD

**Issue by treeowl** [haskell/stm#13]
Currently, a `TArray` is a *boxed* `Array` of `TVar`s. This seems kind of silly. If `TArray` is used at all, the array should surely be unboxed to reduce indirection. Nowadays, that means futzing with `ArrayArray#`, but we'll soon have `UnliftedArray#`.

**Comment by simonmar** [comment]
Indeed. Let's wait for `UnliftedArray#` and then fix this.

**Comment by lehins** [comment]
Here seems to be a related and a bit dated ticket: https://ghc.haskell.org/trac/ghc/ticket/634

**Comment by treeowl** [comment]
We now have `UnliftedArray#`.
