### ISSUE TITLE
stateTVar isn't strict

### ISSUE THREAD

**Issue by KingoftheHomeless** [haskell/stm#30]
From Control.Concurrent.STM.TVar:
```haskell
stateTVar :: TVar s -> (s -> (a, s)) -> STM a
stateTVar var f = do
   s <- readTVar var
   let (a, s') = f s -- since we destructure this, we are strict in f
   writeTVar var s'
   return a
```
The comment is incorrect, since `let`-bindings pattern-match lazily. In order to make this strict, a bang pattern is needed:
```haskell
let !(a, s') = f s -- since we destructure this, we are strict in f
```

**Comment by Fuuzetsu** [comment]
Test-case:
```hs
main :: IO ()
main = do
    v <- newTVarIO (7 :: Int)
    x <- atomically $ do
        stateTVar v (error "strict in f")
        writeTVar v 8
        readTVar v
    print x
```
If we add bang pattern to stateTVar then the code crashes.

I think we should probably add `stateTVar'` as an equivalent of `modifyTVar'`. But it's so simple to implement that perhaps it shouldn't even live in the library and we should only fix the incorrect comment.

**Comment by KingoftheHomeless** [comment]
I would argue that the version of `stateTVar` that is strict in the tuple would be _much_ more useful than the one that isn't, since it allows you to control what components of the result are strict by `seq`-ing them to the tuple, while the lazy version doesn't allow you to control strictness at all. In fact, the strict version is more general than the lazy one, since `stateTVarLazy f = stateTVarStrict (\a -> let ~(a', b) = f a in (a', b))`.

**Comment by infinity0** [comment]
Sorry; I wrote the original code in #14 and was less familiar with strictness then, I assumed it was fine as it passed review. FWIW, I did intend the strict version - the docstring explicitly says it's similar to `modifyTVar'` the strict form. The code is fairly young so I'd guess not many people are using it yet, and that even less people are depending on the lazy behaviour. So perhaps it's worth just adding the bang in a PR, without defining a second function.

**Comment by infinity0** [comment]
> On an unrelated note, perhaps the elements of the tuple should be swapped to mirror atomicModifyIORef?

The intention was to mirror `state` as in `MonadState`, `StateT`, etc.

I speculate that the order in `atomicModifyIORef` comes from an older convention which was swapped, which you still see in the internal definition of IO/ST and GHC internal code.
