### ISSUE TITLE
Huge dependency footprint due to `hashable-1.4.0.0` (via `nats`)

### ISSUE THREAD

**Issue by sol** [haskell/stm#48]
`stm` is a basic library that used to have a tiny dependency footprint.   However, with `hashable-1.4.0.0` this changed considerably.  Some of the dependencies I'm less than exited about are:

```
base-orphans 
functor-classes-compat
ghc-bignum-orphans
transformers-compat
```

I'm not sure for what reason `hashable` has to depend on those, but it can lead to all kinds of build issues that are hard to diagnose (depending on the install plan you end up with).  In my specific case, I have code that works on CI (with `--enable-tests`) but fails for older compilers when installed from Hackage.

Is there a chance that we can address this, either in `stm`, `nats` or `hashable`.

**Comment by Fuuzetsu** [comment]
`stm` change: https://github.com/haskell/stm/commit/ee84fe2ab126b2d17ea07be701c46515cdf3756b
`hashable` change: https://github.com/haskell-unordered-containers/hashable/commit/b618850c2edef5aaf8bad35420044eff14f621de

Looking at `stm` change, it has been the case for 3 years and only impacts compiler versions before 7.10... Seems surprising to hit this now.

**Comment by sol** [comment]
It's not the `stm` change that pulled in those dependencies, it's the recent change to `hashable`.

**Comment by bgamari** [comment]
`stm` only depends upon `nats` when built with rather old GHC versions. Moreover, the `hashable` dependency of `nats` is optional via the `hashable` flag. Perhaps this addresses your concern?

**Comment by sol** [comment]
In my specific situation it works to just "vendor" a copy of `stm-2.5.0.1/Control/Concurrent/STM/TMVar.hs`.  This is not beautiful but saves me 10 dependencies for older versions of GHC:

- `base-orphans`
- `functor-classes-compat`
- `generic-deriving`
- `hashable`
- `mtl`
- `nats`
- `stm`
- `text`
- `th-abstraction`
- `transformers-compat`

As for `stm` depending on `nats`: It's probably too late to do something about it.  However, personally, I can't justify the benefit to weight ratio of that change***.


*** Not only because of the `nats` dependency, but also because it was technically a breaking change for, by my standards, little tangible benefit.
