### ISSUE TITLE
Support `lengthTBQueue` by storing the initial capacity

### ISSUE THREAD

**Issue by mitchellwrosen** [haskell/stm#8]
It would be helpful to get the current number of elements written to a `TBQueue`.

```haskell
lengthTBQueue :: TBQueue a -> STM Int
```

I looked at the source; this isn't possible in `O(1)` - it's `length readEnd ++ length writeEnd`.

However, if we store the initial capacity, then it's just `cap - r - w`:

```haskell
data TBQueue a
  = TBQueue (TVar Int) -- Read capacity
            (TVar [a]) -- Read end
            (TVar Int) -- Write capacity
            (TVar [a]) -- Write end
            Int -- Initial capacity

lengthTBQueue :: TBQueue a -> STM Int
lengthTBQueue (TBQueue rsize _ wsize _ cap) = do
  r <- readTVar rsize
  w <- readTVar wsize
  return (cap - r - w)
```

**Comment by Fuuzetsu** [comment]
Why not just hold onto this value yourself? Even wrap the queue in a data type if you're feeling fancy.

**Comment by mitchellwrosen** [comment]
Holding onto the initial capacity isn't enough since you can't get the `TBQueue`'s inner read/write capacity vars either.

But to your point, yes you can make your own type and track the capacity with a `TVar`:

```haskell
data MyTBQueue a = MyTBQueue (TBQueue a) (TVar Int)
```

**Comment by simonmar** [comment]
Seems reasonable to me. Someone want to submit a PR?
